<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Description>This package adds RefreshToken and LastRefreshTokenTime to tUserGitHub table.</Description>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CK.DB.User.UserGitHub\CK.DB.User.UserGitHub.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="**\*.sql;**\*.tql;**\*.y4" />
  </ItemGroup>

</Project>